import time
import hmac
import hashlib
from typing import Tuple
from .config import settings

def verify_exam_session_token(token: str, expected_exam_id: str, expected_student_id: str) -> Tuple[bool, str]:
    """
    Cryptographically verifies candidate examSessionToken generated by HRTA CBT Controller.
    Format: {examId}.{studentId}.{timestampMs}.{hmacSha256Hex}
    """
    if not token or not isinstance(token, str):
        return False, "Missing or invalid exam session token header (x-exam-session-token)."

    parts = token.strip().split(".")
    if len(parts) != 4:
        return False, "Malformed exam session token format."

    token_exam_id, token_student_id, timestamp_str, signature = parts

    if token_exam_id != expected_exam_id or token_student_id != expected_student_id:
        return False, "Exam session token does not match the active candidate and exam."

    try:
        timestamp_ms = int(timestamp_str)
    except ValueError:
        return False, "Invalid timestamp in session token."

    now_ms = int(time.time() * 1000)
    # 24-hour validity window with 5 min future clock skew tolerance
    if (now_ms - timestamp_ms) > (24 * 60 * 60 * 1000) or timestamp_ms > (now_ms + 5 * 60 * 1000):
        return False, "Exam session token has expired. Please re-verify login."

    secret = settings.SUPER_ADMIN_SECRET
    if not secret:
        # If secret is unconfigured during initial dev setup, allow with warning
        return True, "DEV_MODE_NO_SECRET"

    expected_sig = hmac.new(
        secret.encode("utf-8"),
        f"{token_exam_id}:{token_student_id}:{timestamp_ms}".encode("utf-8"),
        hashlib.sha256
    ).hexdigest()

    if not hmac.compare_digest(signature.lower(), expected_sig.lower()):
        return False, "Cryptographic signature forgery detected in exam session token."

    return True, "AUTHENTIC_SESSION"
